-- MySQL Script generated by MySQL Workbench
-- Sat Jul 15 13:00:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jsday
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jsday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jsday` DEFAULT CHARACTER SET utf8 ;
USE `jsday` ;

-- -----------------------------------------------------
-- Table `jsday`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`usuario` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `nascimento` DATE NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`cargo` (
  `idcargo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`politico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`politico` (
  `idpoliticos` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `cargo_idcargo` INT NOT NULL,
  PRIMARY KEY (`idpoliticos`),
  INDEX `fk_politico_cargo_idx` (`cargo_idcargo` ASC),
  CONSTRAINT `fk_politico_cargo`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `jsday`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`causa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`causa` (
  `idcausa` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `local` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `usuario_iduser` INT NOT NULL,
  `qtd` INT NOT NULL,
  PRIMARY KEY (`idcausa`),
  INDEX `fk_causa_usuario1_idx` (`usuario_iduser` ASC),
  CONSTRAINT `fk_causa_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `jsday`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`apoio` (
  `idapoio` INT NOT NULL,
  `causa_idcausa` INT NOT NULL,
  PRIMARY KEY (`idapoio`),
  INDEX `fk_apoio_causa1_idx` (`causa_idcausa` ASC),
  CONSTRAINT `fk_apoio_causa1`
    FOREIGN KEY (`causa_idcausa`)
    REFERENCES `jsday`.`causa` (`idcausa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`apoio_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`apoio_has_usuario` (
  `apoio_idapoio` INT NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`apoio_idapoio`, `usuario_iduser`),
  INDEX `fk_apoio_has_usuario_usuario1_idx` (`usuario_iduser` ASC),
  INDEX `fk_apoio_has_usuario_apoio1_idx` (`apoio_idapoio` ASC),
  CONSTRAINT `fk_apoio_has_usuario_apoio1`
    FOREIGN KEY (`apoio_idapoio`)
    REFERENCES `jsday`.`apoio` (`idapoio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apoio_has_usuario_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `jsday`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jsday`.`politico_has_causa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jsday`.`politico_has_causa` (
  `politico_idpoliticos` INT NOT NULL,
  `causa_idcausa` INT NOT NULL,
  PRIMARY KEY (`politico_idpoliticos`, `causa_idcausa`),
  INDEX `fk_politico_has_causa_causa1_idx` (`causa_idcausa` ASC),
  INDEX `fk_politico_has_causa_politico1_idx` (`politico_idpoliticos` ASC),
  CONSTRAINT `fk_politico_has_causa_politico1`
    FOREIGN KEY (`politico_idpoliticos`)
    REFERENCES `jsday`.`politico` (`idpoliticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_politico_has_causa_causa1`
    FOREIGN KEY (`causa_idcausa`)
    REFERENCES `jsday`.`causa` (`idcausa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
